# Generated by Django 5.2.1 on 2025-06-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_remove_stock_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='categoria',
            field=models.CharField(default='Sin categoría', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='nombre_producto',
            field=models.CharField(default='Sin categoría', max_length=100),
        ),
    ]
