# Generated by Django 5.2.1 on 2025-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_stock_categoria_stock_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.CharField(default='Sin categoría', max_length=80),
        ),
    ]
