# Generated by Django 5.2.1 on 2025-06-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_inventario_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock',
            field=models.CharField(default='Sin categoría', max_length=80),
        ),
    ]
