# Generated by Django 5.2.1 on 2025-06-24 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_rename_producto_venta_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
            preserve_default=False,
        ),
    ]
